version: '3.1'

services:
  db:
    build: .
    container_name: kanguru-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=kanguru

  dbtest:
    build: .
    container_name: teste-kanguru-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=kanguru
